-- ONE TO ONE
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE EMPLOYEE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  account_id INT(11) NOT NULL
);

CREATE TABLE ACCOUNT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  acc_number VARCHAR(250) NOT NULL
);



-- ONE TO MANY
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS PHONE;
DROP TABLE IF EXISTS STUDENT_PHONE;

CREATE TABLE STUDENT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  account_id INT(11) NOT NULL
);

CREATE TABLE PHONE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  number VARCHAR(250) NOT NULL,
  type VARCHAR(250) NOT NULL
);
CREATE TABLE STUDENT_PHONE (
  student_id INT NOT NULL,
  phone_id INT NOT NULL
);

CREATE TABLE COURSE (
  id INT NOT NULL,
  name VARCHAR(250) NOT NULL,
  lastUpdatedDate date ,
  createdDate date
);

CREATE TABLE STUDENT_COURSE (
  student_id INT NOT NULL,
  course_id INT NOT NULL
);

-- Many To Many
DROP TABLE IF EXISTS SUBSCRIPTION;
DROP TABLE IF EXISTS READER;
DROP TABLE IF EXISTS READER_SUBSCRIPTION;

CREATE TABLE SUBSCRIPTION (
  id INT NOT NULL,
  name VARCHAR(250) NOT NULL
);

CREATE TABLE READER_SUBSCRIPTION (
  subscription_id INT NOT NULL,
  reader_id VARCHAR(250) NOT NULL
);

CREATE TABLE READER (
  id INT NOT NULL,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL
);
